#!/bin/bash
git checkout gradle/macros/trikeshed-lib.gradle
sed -i 's/if (cpuKotlin.targets.findByName("linux") == null) cpuKotlin.linuxX64("linux")/if (cpuKotlin.targets.findByName("linux") == null) {\n            cpuKotlin.linuxX64("linux") {\n                binaries.executable("interrogateCpuNative") {\n                    entryPoint = "borg.trikeshed.cpucache.main"\n                }\n            }\n        } else {\n            def linuxTarget = cpuKotlin.targets.getByName("linux")\n            linuxTarget.binaries.executable("interrogateCpuNative") {\n                entryPoint = "borg.trikeshed.cpucache.main"\n            }\n        }/g' gradle/macros/trikeshed-lib.gradle

sed -i 's/if (cpuKotlin.targets.findByName("linuxArm64") == null) cpuKotlin.linuxArm64()/if (cpuKotlin.targets.findByName("linuxArm64") == null) {\n            cpuKotlin.linuxArm64("linuxArm64") {\n                binaries.executable("interrogateCpuNative") {\n                    entryPoint = "borg.trikeshed.cpucache.main"\n                }\n            }\n        } else {\n            def linuxArm64Target = cpuKotlin.targets.getByName("linuxArm64")\n            linuxArm64Target.binaries.executable("interrogateCpuNative") {\n                entryPoint = "borg.trikeshed.cpucache.main"\n            }\n        }/g' gradle/macros/trikeshed-lib.gradle

sed -i 's/cpuKotlin.macosX64()/cpuKotlin.macosX64("macos") {\n                binaries.executable("interrogateCpuNative") {\n                    entryPoint = "borg.trikeshed.cpucache.main"\n                }\n            }/g' gradle/macros/trikeshed-lib.gradle

sed -i 's/tasks.register("interrogateCpu", JavaExec) {/tasks.register("interrogateCpuNative", Exec) {\n            group = "cpu-cache"\n            description = "Interrogate CPU cache topology using Native binary and print Confix JSON"\n            def isMac = System.getProperty("os.name") == "Mac OS X"\n            def isArm = System.getProperty("os.arch") == "aarch64"\n            def targetName = "linux"\n            if (isMac) {\n                targetName = isArm ? "macosArm64" : "macosX64"\n            } else if (isArm) {\n                targetName = "linuxArm64"\n            }\n            if (targetName == "macosX64") targetName = "macos"\n            def capitalizedName = targetName.substring(0, 1).toUpperCase() + targetName.substring(1)\n            dependsOn("linkInterrogateCpuNativeReleaseExecutable${capitalizedName}")\n            def buildDir = layout.buildDirectory.get().asFile\n            commandLine("${buildDir}\/bin\/${targetName}\/interrogateCpuNativeReleaseExecutable\/interrogateCpuNative.kexe")\n        }\n        tasks.register("interrogateCpu", JavaExec) {/g' gradle/macros/trikeshed-lib.gradle
