@file:Suppress("EXPECT_ACTUAL_CLASSIFIERS_ARE_IN_BETA_WARNING", "RedundantVisibilityModifier", "unused")

package borg.trikeshed.userspace.nio.file

// Generated from Amazon Corretto JDK 25 java.base NIO public/protected API via javap.
// Declarations intentionally mirror JDK taxonomy and contain no implementations.
public class Files {
    companion object {
        fun newInputStream(p0: borg.trikeshed.userspace.nio.file.Path, vararg p1: borg.trikeshed.userspace.nio.file.OpenOption): Any = TODO("NIO common stub")
        fun newOutputStream(p0: borg.trikeshed.userspace.nio.file.Path, vararg p1: borg.trikeshed.userspace.nio.file.OpenOption): Any = TODO("NIO common stub")
        fun newByteChannel(p0: borg.trikeshed.userspace.nio.file.Path, p1: Set<out borg.trikeshed.userspace.nio.file.OpenOption>, vararg p2: borg.trikeshed.userspace.nio.file.attribute.FileAttribute<*>): borg.trikeshed.userspace.nio.channels.SeekableByteChannel = TODO("NIO common stub")
        fun newByteChannel(p0: borg.trikeshed.userspace.nio.file.Path, vararg p1: borg.trikeshed.userspace.nio.file.OpenOption): borg.trikeshed.userspace.nio.channels.SeekableByteChannel = TODO("NIO common stub")
        fun newDirectoryStream(p0: borg.trikeshed.userspace.nio.file.Path): borg.trikeshed.userspace.nio.file.DirectoryStream<borg.trikeshed.userspace.nio.file.Path> = TODO("NIO common stub")
        fun newDirectoryStream(p0: borg.trikeshed.userspace.nio.file.Path, p1: String): borg.trikeshed.userspace.nio.file.DirectoryStream<borg.trikeshed.userspace.nio.file.Path> = TODO("NIO common stub")
        fun newDirectoryStream(p0: borg.trikeshed.userspace.nio.file.Path, p1: borg.trikeshed.userspace.nio.file.DirectoryStream.Filter<in borg.trikeshed.userspace.nio.file.Path>): borg.trikeshed.userspace.nio.file.DirectoryStream<borg.trikeshed.userspace.nio.file.Path> = TODO("NIO common stub")
        fun createFile(p0: borg.trikeshed.userspace.nio.file.Path, vararg p1: borg.trikeshed.userspace.nio.file.attribute.FileAttribute<*>): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun createDirectory(p0: borg.trikeshed.userspace.nio.file.Path, vararg p1: borg.trikeshed.userspace.nio.file.attribute.FileAttribute<*>): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun createDirectories(p0: borg.trikeshed.userspace.nio.file.Path, vararg p1: borg.trikeshed.userspace.nio.file.attribute.FileAttribute<*>): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun createTempFile(p0: borg.trikeshed.userspace.nio.file.Path, p1: String, p2: String, vararg p3: borg.trikeshed.userspace.nio.file.attribute.FileAttribute<*>): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun createTempFile(p0: String, p1: String, vararg p2: borg.trikeshed.userspace.nio.file.attribute.FileAttribute<*>): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun createTempDirectory(p0: borg.trikeshed.userspace.nio.file.Path, p1: String, vararg p2: borg.trikeshed.userspace.nio.file.attribute.FileAttribute<*>): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun createTempDirectory(p0: String, vararg p1: borg.trikeshed.userspace.nio.file.attribute.FileAttribute<*>): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun createSymbolicLink(p0: borg.trikeshed.userspace.nio.file.Path, p1: borg.trikeshed.userspace.nio.file.Path, vararg p2: borg.trikeshed.userspace.nio.file.attribute.FileAttribute<*>): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun createLink(p0: borg.trikeshed.userspace.nio.file.Path, p1: borg.trikeshed.userspace.nio.file.Path): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun delete(p0: borg.trikeshed.userspace.nio.file.Path): Unit = TODO("NIO common stub")
        fun deleteIfExists(p0: borg.trikeshed.userspace.nio.file.Path): Boolean = TODO("NIO common stub")
        fun copy(p0: borg.trikeshed.userspace.nio.file.Path, p1: borg.trikeshed.userspace.nio.file.Path, vararg p2: borg.trikeshed.userspace.nio.file.CopyOption): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun move(p0: borg.trikeshed.userspace.nio.file.Path, p1: borg.trikeshed.userspace.nio.file.Path, vararg p2: borg.trikeshed.userspace.nio.file.CopyOption): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun readSymbolicLink(p0: borg.trikeshed.userspace.nio.file.Path): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun getFileStore(p0: borg.trikeshed.userspace.nio.file.Path): borg.trikeshed.userspace.nio.file.FileStore = TODO("NIO common stub")
        fun isSameFile(p0: borg.trikeshed.userspace.nio.file.Path, p1: borg.trikeshed.userspace.nio.file.Path): Boolean = TODO("NIO common stub")
        fun mismatch(p0: borg.trikeshed.userspace.nio.file.Path, p1: borg.trikeshed.userspace.nio.file.Path): Long = TODO("NIO common stub")
        fun isHidden(p0: borg.trikeshed.userspace.nio.file.Path): Boolean = TODO("NIO common stub")
        fun probeContentType(p0: borg.trikeshed.userspace.nio.file.Path): String = TODO("NIO common stub")
        fun <V : borg.trikeshed.userspace.nio.file.attribute.FileAttributeView> getFileAttributeView(p0: borg.trikeshed.userspace.nio.file.Path, p1: kotlin.reflect.KClass<V>, vararg p2: borg.trikeshed.userspace.nio.file.LinkOption): V = TODO("NIO common stub")
        fun <A : borg.trikeshed.userspace.nio.file.attribute.BasicFileAttributes> readAttributes(p0: borg.trikeshed.userspace.nio.file.Path, p1: kotlin.reflect.KClass<A>, vararg p2: borg.trikeshed.userspace.nio.file.LinkOption): A = TODO("NIO common stub")
        fun setAttribute(p0: borg.trikeshed.userspace.nio.file.Path, p1: String, p2: Any, vararg p3: borg.trikeshed.userspace.nio.file.LinkOption): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun getAttribute(p0: borg.trikeshed.userspace.nio.file.Path, p1: String, vararg p2: borg.trikeshed.userspace.nio.file.LinkOption): Any = TODO("NIO common stub")
        fun readAttributes(p0: borg.trikeshed.userspace.nio.file.Path, p1: String, vararg p2: borg.trikeshed.userspace.nio.file.LinkOption): Map<String, Any> = TODO("NIO common stub")
        fun getPosixFilePermissions(p0: borg.trikeshed.userspace.nio.file.Path, vararg p1: borg.trikeshed.userspace.nio.file.LinkOption): Set<borg.trikeshed.userspace.nio.file.attribute.PosixFilePermission> = TODO("NIO common stub")
        fun setPosixFilePermissions(p0: borg.trikeshed.userspace.nio.file.Path, p1: Set<borg.trikeshed.userspace.nio.file.attribute.PosixFilePermission>): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun getOwner(p0: borg.trikeshed.userspace.nio.file.Path, vararg p1: borg.trikeshed.userspace.nio.file.LinkOption): borg.trikeshed.userspace.nio.file.attribute.UserPrincipal = TODO("NIO common stub")
        fun setOwner(p0: borg.trikeshed.userspace.nio.file.Path, p1: borg.trikeshed.userspace.nio.file.attribute.UserPrincipal): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun isSymbolicLink(p0: borg.trikeshed.userspace.nio.file.Path): Boolean = TODO("NIO common stub")
        fun isDirectory(p0: borg.trikeshed.userspace.nio.file.Path, vararg p1: borg.trikeshed.userspace.nio.file.LinkOption): Boolean = TODO("NIO common stub")
        fun isRegularFile(p0: borg.trikeshed.userspace.nio.file.Path, vararg p1: borg.trikeshed.userspace.nio.file.LinkOption): Boolean = TODO("NIO common stub")
        fun getLastModifiedTime(p0: borg.trikeshed.userspace.nio.file.Path, vararg p1: borg.trikeshed.userspace.nio.file.LinkOption): borg.trikeshed.userspace.nio.file.attribute.FileTime = TODO("NIO common stub")
        fun setLastModifiedTime(p0: borg.trikeshed.userspace.nio.file.Path, p1: borg.trikeshed.userspace.nio.file.attribute.FileTime): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun size(p0: borg.trikeshed.userspace.nio.file.Path): Long = TODO("NIO common stub")
        fun exists(p0: borg.trikeshed.userspace.nio.file.Path, vararg p1: borg.trikeshed.userspace.nio.file.LinkOption): Boolean = TODO("NIO common stub")
        fun notExists(p0: borg.trikeshed.userspace.nio.file.Path, vararg p1: borg.trikeshed.userspace.nio.file.LinkOption): Boolean = TODO("NIO common stub")
        fun isReadable(p0: borg.trikeshed.userspace.nio.file.Path): Boolean = TODO("NIO common stub")
        fun isWritable(p0: borg.trikeshed.userspace.nio.file.Path): Boolean = TODO("NIO common stub")
        fun isExecutable(p0: borg.trikeshed.userspace.nio.file.Path): Boolean = TODO("NIO common stub")
        fun walkFileTree(p0: borg.trikeshed.userspace.nio.file.Path, p1: Set<borg.trikeshed.userspace.nio.file.FileVisitOption>, p2: Int, p3: borg.trikeshed.userspace.nio.file.FileVisitor<in borg.trikeshed.userspace.nio.file.Path>): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun walkFileTree(p0: borg.trikeshed.userspace.nio.file.Path, p1: borg.trikeshed.userspace.nio.file.FileVisitor<in borg.trikeshed.userspace.nio.file.Path>): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun newBufferedReader(p0: borg.trikeshed.userspace.nio.file.Path, p1: borg.trikeshed.userspace.nio.charset.Charset): Any = TODO("NIO common stub")
        fun newBufferedReader(p0: borg.trikeshed.userspace.nio.file.Path): Any = TODO("NIO common stub")
        fun newBufferedWriter(p0: borg.trikeshed.userspace.nio.file.Path, p1: borg.trikeshed.userspace.nio.charset.Charset, vararg p2: borg.trikeshed.userspace.nio.file.OpenOption): Any = TODO("NIO common stub")
        fun newBufferedWriter(p0: borg.trikeshed.userspace.nio.file.Path, vararg p1: borg.trikeshed.userspace.nio.file.OpenOption): Any = TODO("NIO common stub")
        fun copy(p0: Any, p1: borg.trikeshed.userspace.nio.file.Path, vararg p2: borg.trikeshed.userspace.nio.file.CopyOption): Long = TODO("NIO common stub")
        fun copy(p0: borg.trikeshed.userspace.nio.file.Path, p1: Any): Long = TODO("NIO common stub")
        fun readAllBytes(p0: borg.trikeshed.userspace.nio.file.Path): ByteArray = TODO("NIO common stub")
        fun readString(p0: borg.trikeshed.userspace.nio.file.Path): String = TODO("NIO common stub")
        fun readString(p0: borg.trikeshed.userspace.nio.file.Path, p1: borg.trikeshed.userspace.nio.charset.Charset): String = TODO("NIO common stub")
        fun readAllLines(p0: borg.trikeshed.userspace.nio.file.Path, p1: borg.trikeshed.userspace.nio.charset.Charset): List<String> = TODO("NIO common stub")
        fun readAllLines(p0: borg.trikeshed.userspace.nio.file.Path): List<String> = TODO("NIO common stub")
        fun write(p0: borg.trikeshed.userspace.nio.file.Path, p1: ByteArray, vararg p2: borg.trikeshed.userspace.nio.file.OpenOption): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun write(p0: borg.trikeshed.userspace.nio.file.Path, p1: Iterable<out CharSequence>, p2: borg.trikeshed.userspace.nio.charset.Charset, vararg p3: borg.trikeshed.userspace.nio.file.OpenOption): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun write(p0: borg.trikeshed.userspace.nio.file.Path, p1: Iterable<out CharSequence>, vararg p2: borg.trikeshed.userspace.nio.file.OpenOption): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun writeString(p0: borg.trikeshed.userspace.nio.file.Path, p1: CharSequence, vararg p2: borg.trikeshed.userspace.nio.file.OpenOption): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun writeString(p0: borg.trikeshed.userspace.nio.file.Path, p1: CharSequence, p2: borg.trikeshed.userspace.nio.charset.Charset, vararg p3: borg.trikeshed.userspace.nio.file.OpenOption): borg.trikeshed.userspace.nio.file.Path = TODO("NIO common stub")
        fun list(p0: borg.trikeshed.userspace.nio.file.Path): Sequence<borg.trikeshed.userspace.nio.file.Path> = TODO("NIO common stub")
        fun walk(p0: borg.trikeshed.userspace.nio.file.Path, p1: Int, vararg p2: borg.trikeshed.userspace.nio.file.FileVisitOption): Sequence<borg.trikeshed.userspace.nio.file.Path> = TODO("NIO common stub")
        fun walk(p0: borg.trikeshed.userspace.nio.file.Path, vararg p1: borg.trikeshed.userspace.nio.file.FileVisitOption): Sequence<borg.trikeshed.userspace.nio.file.Path> = TODO("NIO common stub")
        fun find(p0: borg.trikeshed.userspace.nio.file.Path, p1: Int, p2: Pair<borg.trikeshed.userspace.nio.file.Path, borg.trikeshed.userspace.nio.file.attribute.BasicFileAttributes>, vararg p3: borg.trikeshed.userspace.nio.file.FileVisitOption): Sequence<borg.trikeshed.userspace.nio.file.Path> = TODO("NIO common stub")
        fun lines(p0: borg.trikeshed.userspace.nio.file.Path, p1: borg.trikeshed.userspace.nio.charset.Charset): Sequence<String> = TODO("NIO common stub")
        fun lines(p0: borg.trikeshed.userspace.nio.file.Path): Sequence<String> = TODO("NIO common stub")
    }
}
