package borg.trikeshed.forge.ui

data class WidgetShowcasePage(
    val id: String,
    val title: String,
    val subtitle: String,
    val layout: WidgetShowcaseLayout,
    val widgets: List<WidgetShowcaseWidget>,
    val templateNotes: List<String> = emptyList(),
)

enum class WidgetShowcaseLayout {
    HERO,
    SPLIT,
    GRID,
    STACK,
    DOC,
    RADAR,
}

enum class WidgetShowcaseTone {
    PRIMARY,
    SUCCESS,
    WARNING,
    DANGER,
    MUTED,
}

enum class WidgetShowcaseKind {
    SHELL,
    BUTTON,
    CHIP,
    CARD,
    INPUT,
    METRIC,
    INSPECTOR,
    TIMELINE,
}

data class WidgetShowcaseWidget(
    val id: String,
    val kind: WidgetShowcaseKind,
    val title: String,
    val value: String,
    val body: String,
    val tone: WidgetShowcaseTone = WidgetShowcaseTone.PRIMARY,
    val accent: String = "#7aa2f7",
    val badges: List<String> = emptyList(),
    val ctas: List<String> = emptyList(),
    val links: List<String> = emptyList(),
)

fun widgetShowcasePages(): List<WidgetShowcasePage> = listOf(
    WidgetShowcasePage(
        id = "dev-atlas",
        title = "Development atlas",
        subtitle = "A living document that opens the gallery like an annotated spec: table of contents, linked sections, and routes into the blackboard terrain.",
        layout = WidgetShowcaseLayout.DOC,
        widgets = listOf(
            WidgetShowcaseWidget(
                id = "doc-cover",
                kind = WidgetShowcaseKind.SHELL,
                title = "Atlas cover",
                value = "open doc",
                body = "The gallery opens here first, like a technical document that already knows its own map and the places it can jump to next.",
                tone = WidgetShowcaseTone.MUTED,
                accent = "#5b6b7a",
                badges = listOf("document", "launcher", "overview"),
                links = listOf("doc-outline", "doc-blackboard", "doc-launch"),
            ),
            WidgetShowcaseWidget(
                id = "doc-outline",
                kind = WidgetShowcaseKind.INSPECTOR,
                title = "Outline",
                value = "6 sections",
                body = "A table of contents that explains the terrain: shell, board, radar, graph links, and how the movie export stays readable.",
                tone = WidgetShowcaseTone.PRIMARY,
                accent = "#7aa2f7",
                badges = listOf("toc", "linked"),
                ctas = listOf("jump to blackboard", "jump to board"),
                links = listOf("doc-cover", "doc-blackboard", "doc-kanban", "doc-launch"),
            ),
            WidgetShowcaseWidget(
                id = "doc-blackboard",
                kind = WidgetShowcaseKind.CARD,
                title = "Blackboard terrain",
                value = "radar / scope",
                body = "A graph surface that turns the blackboard into an RTS-like map: zoom, pan, flip, and keep the selected node in the center of the story.",
                tone = WidgetShowcaseTone.SUCCESS,
                accent = "#73daca",
                badges = listOf("terrain", "graph", "radar"),
                links = listOf("doc-cover", "doc-outline", "doc-kanban", "doc-links"),
            ),
            WidgetShowcaseWidget(
                id = "doc-kanban",
                kind = WidgetShowcaseKind.METRIC,
                title = "Kanban depth",
                value = "shadow / reflection",
                body = "The board is still a board, but it picks up depth cues, material sheen, and dynamic scaling so the panels feel larger than the viewport.",
                tone = WidgetShowcaseTone.WARNING,
                accent = "#e0af68",
                badges = listOf("lighting", "shadow", "scale"),
                links = listOf("doc-blackboard", "doc-links", "doc-launch"),
            ),
            WidgetShowcaseWidget(
                id = "doc-links",
                kind = WidgetShowcaseKind.TIMELINE,
                title = "Transition rail",
                value = "forge ↔ notion",
                body = "A narrative rail that links the notion-like docs view to the forge widgets and the blackboard radar without breaking the reading flow.",
                tone = WidgetShowcaseTone.PRIMARY,
                accent = "#bb9af7",
                badges = listOf("transition", "linkage"),
                links = listOf("doc-outline", "doc-blackboard", "doc-launch"),
            ),
            WidgetShowcaseWidget(
                id = "doc-launch",
                kind = WidgetShowcaseKind.BUTTON,
                title = "Launch gallery",
                value = "open live",
                body = "A direct entry point into the gallery, so the document can unfold into the interactive showcase without changing context.",
                tone = WidgetShowcaseTone.DANGER,
                accent = "#f7768e",
                ctas = listOf("open showcase", "open board", "open radar"),
                links = listOf("doc-cover", "doc-links"),
            ),
        ),
        templateNotes = listOf(
            "First screen should read like a document, not a menu",
            "The outline should act as a transition map into the live gallery",
            "Use links and depth cues to make the text feel navigable",
        ),
    ),
    WidgetShowcasePage(
        id = "shell-hero",
        title = "Shell hero",
        subtitle = "The top-level page scaffold: brand strip, call-to-action row, and a status rail.",
        layout = WidgetShowcaseLayout.HERO,
        widgets = listOf(
            WidgetShowcaseWidget(
                id = "shell-brand",
                kind = WidgetShowcaseKind.SHELL,
                title = "Forge shell",
                value = "1280 × 800",
                body = "A page frame that anchors the app, keeps the chrome stable, and leaves room for the working surface.",
                tone = WidgetShowcaseTone.MUTED,
                accent = "#5b6b7a",
                badges = listOf("chrome", "shell", "navigation"),
            ),
            WidgetShowcaseWidget(
                id = "shell-primary",
                kind = WidgetShowcaseKind.BUTTON,
                title = "Primary action",
                value = "record",
                body = "The emphatic button that starts a capture or launches the live flow for a showcase scene.",
                tone = WidgetShowcaseTone.PRIMARY,
                accent = "#7aa2f7",
                ctas = listOf("record movie", "open live view"),
                links = listOf("shell-brand", "shell-status"),
            ),
            WidgetShowcaseWidget(
                id = "shell-status",
                kind = WidgetShowcaseKind.CHIP,
                title = "Status chip",
                value = "live",
                body = "A tiny feedback element that advertises state without forcing the user to read a long label.",
                tone = WidgetShowcaseTone.SUCCESS,
                accent = "#9ece6a",
                badges = listOf("online", "ready"),
                links = listOf("shell-brand"),
            ),
            WidgetShowcaseWidget(
                id = "shell-metric",
                kind = WidgetShowcaseKind.METRIC,
                title = "Capture metric",
                value = "30 fps",
                body = "A dense readout that explains how the render loop will behave when the scene is recorded to a movie.",
                tone = WidgetShowcaseTone.WARNING,
                accent = "#e0af68",
                badges = listOf("fps", "export"),
                links = listOf("shell-primary"),
            ),
        ),
        templateNotes = listOf(
            "Hero banner with one big CTA",
            "Three summary cards under the fold",
            "Sticky status strip in the footer",
        ),
    ),
    WidgetShowcasePage(
        id = "split-inspector",
        title = "Split inspector",
        subtitle = "A dense workbench layout: selection rail on the left, detail inspector on the right.",
        layout = WidgetShowcaseLayout.SPLIT,
        widgets = listOf(
            WidgetShowcaseWidget(
                id = "split-list",
                kind = WidgetShowcaseKind.CARD,
                title = "Item rail",
                value = "3 variants",
                body = "A list surface that lets the user choose which widget family they want to inspect next.",
                tone = WidgetShowcaseTone.PRIMARY,
                accent = "#bb9af7",
                badges = listOf("selectable", "scrollable"),
                links = listOf("split-input", "split-inspector-widget"),
            ),
            WidgetShowcaseWidget(
                id = "split-input",
                kind = WidgetShowcaseKind.INPUT,
                title = "Search field",
                value = "type to filter",
                body = "A focused field that drives the gallery filter and demonstrates text entry in the shared toolkit.",
                tone = WidgetShowcaseTone.MUTED,
                accent = "#7dcfff",
                badges = listOf("input", "filter"),
                ctas = listOf("clear", "apply filter"),
                links = listOf("split-list", "split-inspector-widget"),
            ),
            WidgetShowcaseWidget(
                id = "split-inspector-widget",
                kind = WidgetShowcaseKind.INSPECTOR,
                title = "Inspector",
                value = "selected widget",
                body = "A detail pane that explains the current widget, its role in the page template, and its action surface.",
                tone = WidgetShowcaseTone.SUCCESS,
                accent = "#73daca",
                badges = listOf("details", "selection"),
                links = listOf("split-list", "split-input", "split-badge"),
            ),
            WidgetShowcaseWidget(
                id = "split-badge",
                kind = WidgetShowcaseKind.CHIP,
                title = "Tight badge",
                value = "WIP 3",
                body = "A compact pill that communicates bounded state, like a warning or in-progress count.",
                tone = WidgetShowcaseTone.WARNING,
                accent = "#e0af68",
                badges = listOf("badge", "count"),
                links = listOf("split-inspector-widget"),
            ),
        ),
        templateNotes = listOf(
            "Two-column shell with a fixed rail",
            "Inspector should remain readable while the list scrolls",
            "CTA row stays at the top of the detail column",
        ),
    ),
    WidgetShowcasePage(
        id = "grid-gallery",
        title = "Card gallery",
        subtitle = "A responsive gallery layout for showcasing cards, metrics, and chips side by side.",
        layout = WidgetShowcaseLayout.GRID,
        widgets = listOf(
            WidgetShowcaseWidget(
                id = "grid-card-1",
                kind = WidgetShowcaseKind.CARD,
                title = "Preview card",
                value = "surface",
                body = "A neutral card with a framed surface, used to show elevation and spacing rules.",
                tone = WidgetShowcaseTone.PRIMARY,
                accent = "#7aa2f7",
                badges = listOf("surface", "elevation"),
                links = listOf("grid-card-2", "grid-metric"),
            ),
            WidgetShowcaseWidget(
                id = "grid-card-2",
                kind = WidgetShowcaseKind.CARD,
                title = "Signal card",
                value = "events",
                body = "A more energetic card for live state and signal delivery. Good for status dashboards.",
                tone = WidgetShowcaseTone.SUCCESS,
                accent = "#9ece6a",
                badges = listOf("events", "signal"),
                links = listOf("grid-card-1", "grid-card-3"),
            ),
            WidgetShowcaseWidget(
                id = "grid-card-3",
                kind = WidgetShowcaseKind.CARD,
                title = "Error card",
                value = "retry",
                body = "A danger tone card that draws attention when the page wants to show a failure mode.",
                tone = WidgetShowcaseTone.DANGER,
                accent = "#f7768e",
                badges = listOf("error", "alert"),
                ctas = listOf("retry now"),
                links = listOf("grid-card-2", "grid-metric"),
            ),
            WidgetShowcaseWidget(
                id = "grid-metric",
                kind = WidgetShowcaseKind.METRIC,
                title = "Render budget",
                value = "6 widgets",
                body = "A numeric tile that shows how much space the gallery is using in the current template.",
                tone = WidgetShowcaseTone.WARNING,
                accent = "#e0af68",
                badges = listOf("count", "budget"),
                links = listOf("grid-card-1", "grid-card-3"),
            ),
        ),
        templateNotes = listOf(
            "Responsive grid with equal-height tiles",
            "Cards should keep their metadata aligned",
            "Toned accents distinguish success, warning, and error states",
        ),
    ),
    WidgetShowcasePage(
        id = "stacked-timeline",
        title = "Stacked timeline",
        subtitle = "A vertical composition for annotations, timelines, and persistent footer content.",
        layout = WidgetShowcaseLayout.STACK,
        widgets = listOf(
            WidgetShowcaseWidget(
                id = "stack-timeline",
                kind = WidgetShowcaseKind.TIMELINE,
                title = "Timeline",
                value = "step 3 / 5",
                body = "A vertical running log that explains the scene, useful for recording and narrated demos.",
                tone = WidgetShowcaseTone.MUTED,
                accent = "#bb9af7",
                badges = listOf("timeline", "narration"),
                links = listOf("stack-toolbar", "stack-footer"),
            ),
            WidgetShowcaseWidget(
                id = "stack-toolbar",
                kind = WidgetShowcaseKind.BUTTON,
                title = "Toolbar",
                value = "compact",
                body = "A small action cluster that anchors the layout and keeps the important actions always visible.",
                tone = WidgetShowcaseTone.PRIMARY,
                accent = "#7aa2f7",
                ctas = listOf("edit", "export", "share"),
                links = listOf("stack-timeline", "stack-callout"),
            ),
            WidgetShowcaseWidget(
                id = "stack-footer",
                kind = WidgetShowcaseKind.SHELL,
                title = "Footer strip",
                value = "movie-ready",
                body = "A footer that holds hints, annotations, and the movie export destination without getting in the way.",
                tone = WidgetShowcaseTone.SUCCESS,
                accent = "#73daca",
                badges = listOf("footer", "export"),
                links = listOf("stack-timeline", "stack-callout"),
            ),
            WidgetShowcaseWidget(
                id = "stack-callout",
                kind = WidgetShowcaseKind.CHIP,
                title = "Callout",
                value = "template",
                body = "A concise callout that explains which template is active and why it matters to the current page.",
                tone = WidgetShowcaseTone.WARNING,
                accent = "#e0af68",
                badges = listOf("callout", "layout"),
                links = listOf("stack-footer"),
            ),
        ),
        templateNotes = listOf(
            "Vertical stack for long-form narration",
            "Footer remains anchored while content scrolls",
            "Good home for movie subtitles and annotations",
        ),
    ),
    WidgetShowcasePage(
        id = "blackboard-radar",
        title = "Blackboard terrain",
        subtitle = "A zoomable graph-surface for scopes, Confix paths, and classfile-backed navigation.",
        layout = WidgetShowcaseLayout.RADAR,
        widgets = listOf(
            WidgetShowcaseWidget(
                id = "radar-root",
                kind = WidgetShowcaseKind.SHELL,
                title = "Board root",
                value = "scope /",
                body = "The origin point where the terrain is anchored and the graph can pivot around the current scope.",
                tone = WidgetShowcaseTone.MUTED,
                accent = "#4c566a",
                badges = listOf("root", "scope"),
                links = listOf("radar-taxonomy", "radar-blackboard", "radar-classfile"),
            ),
            WidgetShowcaseWidget(
                id = "radar-taxonomy",
                kind = WidgetShowcaseKind.INSPECTOR,
                title = "Taxonomy lens",
                value = "navigate",
                body = "A navigable lens that turns the board into a linked taxonomy rather than a flat page.",
                tone = WidgetShowcaseTone.PRIMARY,
                accent = "#7aa2f7",
                badges = listOf("taxonomy", "link"),
                ctas = listOf("focus", "descend"),
                links = listOf("radar-root", "radar-blackboard", "radar-gallery"),
            ),
            WidgetShowcaseWidget(
                id = "radar-blackboard",
                kind = WidgetShowcaseKind.CARD,
                title = "Confix blackboard",
                value = "live cells",
                body = "A terrain layer that exposes dynamic blackboard scopes with path-based ad hoc linkage.",
                tone = WidgetShowcaseTone.SUCCESS,
                accent = "#73daca",
                badges = listOf("confix", "scope", "cells"),
                links = listOf("radar-root", "radar-taxonomy", "radar-classfile", "radar-gallery"),
            ),
            WidgetShowcaseWidget(
                id = "radar-classfile",
                kind = WidgetShowcaseKind.TIMELINE,
                title = "Classfile spine",
                value = "ui-tk traits",
                body = "A high-level spine that maps forge-ui artifacts into classfile traits and gallery-video routes.",
                tone = WidgetShowcaseTone.WARNING,
                accent = "#e0af68",
                badges = listOf("classfile", "traits"),
                links = listOf("radar-blackboard", "radar-gallery"),
            ),
            WidgetShowcaseWidget(
                id = "radar-gallery",
                kind = WidgetShowcaseKind.METRIC,
                title = "Gallery video",
                value = "zoom replay",
                body = "A movie-ready node that plays the terrain back at a glance and supports panning through the map.",
                tone = WidgetShowcaseTone.DANGER,
                accent = "#f7768e",
                badges = listOf("video", "radar"),
                links = listOf("radar-root", "radar-classfile"),
            ),
            WidgetShowcaseWidget(
                id = "radar-zoom",
                kind = WidgetShowcaseKind.BUTTON,
                title = "Radar lens",
                value = "flip / scale",
                body = "A minimalist control plane for zooming, panning, and flipping the blackboard terrain.",
                tone = WidgetShowcaseTone.PRIMARY,
                accent = "#bb9af7",
                ctas = listOf("zoom in", "zoom out", "flip view"),
                links = listOf("radar-root", "radar-gallery"),
            ),
        ),
        templateNotes = listOf(
            "Zoom and pan should feel like navigating a terrain map",
            "Edges form the relationship graph and the selected node pulses forward",
            "Dense shadows and highlights make scope changes legible",
        ),
    ),
)
