"use strict";
const {chromium} = require("playwright");
const assert = require("node:assert/strict"), fs = require("node:fs/promises"), os = require("node:os"), path = require("node:path");
const zip = require("../../commonMain/resources/web/vendor/fflate-0.8.2.js");
const base = process.env.ARCHIVE_BASE_URL || "http://127.0.0.1:8896";

(async () => {
  const output = await fs.mkdtemp(path.join(os.tmpdir(), "trikeshed-archive-browser-"));
  const browser = await chromium.launch({headless:true});
  try {
    const page = await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
    const errors = []; page.on("pageerror", error => errors.push(error.message));
    await page.goto(base + "/harness", {waitUntil:"domcontentloaded"});
    await page.waitForFunction(() => typeof Harness !== "undefined" && Harness.ready);
    await page.locator("#archiveBtn").click();
    await page.locator("#archiveDemo").click();
    await page.waitForFunction(() => document.querySelectorAll("#archiveEntries li").length === 6);
    const cid = await page.locator("#archiveCid").inputValue();
    assert.match(cid, /^sha256:[a-f0-9]{64}$/);
    await page.getByRole("button", {name:"archive-demo/README.md",exact:true}).click();
    await page.locator("#archivePreview .mdview").waitFor();
    await page.waitForFunction(() => document.querySelector("#archivePreview .file-meta")?.textContent.includes("% K"));
    await page.screenshot({path:path.join(output,"desktop-inspector.png")});
    const boxes = page.locator("#archiveEntries input:not(:disabled)");
    for (const box of await boxes.all()) await box.uncheck();
    await page.getByRole("checkbox",{name:"Select archive-demo/data/bytes.bin",exact:true}).check();
    let waiting = page.waitForEvent("download"); await page.locator("#archiveDownload").click();
    let downloaded = await waiting;
    assert.equal(downloaded.suggestedFilename(), "bytes.bin");
    assert.deepEqual(await fs.readFile(await downloaded.path()), Buffer.from(Uint8Array.from({length:256}, (_,i)=>i)));
    await page.getByRole("checkbox",{name:"Select archive-demo/README.md",exact:true}).check();
    await page.waitForFunction(() => !document.querySelector("#archiveDownload").disabled);
    waiting = page.waitForEvent("download"); await page.locator("#archiveDownload").click(); downloaded = await waiting;
    assert.deepEqual(Object.keys(zip.unzipSync(await fs.readFile(await downloaded.path()))).sort(), ["archive-demo/README.md","archive-demo/data/bytes.bin"]);
    await page.locator("#archiveLandscape").click();
    await page.locator(".archive-node.note").first().waitFor({state:"attached"});
    assert.equal(await page.locator(".archive-node.note").count(), 5);
    assert.ok(await page.locator(".archive-node.scope .archive-node.scope").count() >= 3);
    assert.equal(await page.locator("#runBtn").isDisabled(), true);
    await page.screenshot({path:path.join(output,"desktop-landscape.png")});
    assert.equal(await page.evaluate(() => {
      const nodes = G.nodes.filter(n=>n.params?.archiveCid);
      return nodes.every(a=>nodes.every(b=>{
        if(a===b||!a._parentScope||a._parentScope!==b._parentScope)return true;
        const x=a.el.getBoundingClientRect(),y=b.el.getBoundingClientRect();
        return x.right<=y.left+1||y.right<=x.left+1||x.bottom<=y.top+1||y.bottom<=x.top+1;
      }));
    }),true,"archive siblings must not overlap");
    assert.ok(await page.locator("#landscape").evaluate(canvas => {
      const pixels=canvas.getContext("2d").getImageData(0,0,canvas.width,canvas.height).data;
      let painted=0;for(let i=3;i<pixels.length;i+=4)if(pixels[i])painted++;return painted>500;
    }));
    const leaf = await page.locator('.archive-inspect[aria-label="Inspect archive-demo/data/bytes.bin"]').boundingBox();
    await page.mouse.move(leaf.x + leaf.width/2, leaf.y + leaf.height/2);
    await page.mouse.wheel(0,-700);
    await page.locator('.archive-inspect[aria-label="Inspect archive-demo/data/bytes.bin"]').click();
    await page.waitForFunction(() => document.querySelector("#archivePreview")?.textContent.includes("00 01 02"));
    await page.getByRole("button",{name:"Close archive",exact:true}).click();
    await page.locator("#storeSaveBtn").click();
    await page.waitForFunction(() => document.querySelector("#status").textContent.startsWith("Published archive-"));
    await page.reload({waitUntil:"domcontentloaded"});
    await page.waitForFunction(() => typeof Harness !== "undefined" && Harness.ready && Harness.selected?.startsWith("archive-"));
    assert.equal(await page.locator(".archive-node.note").count(), 5);
    const mobile = await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
    mobile.on("pageerror", error => errors.push(error.message));
    await mobile.goto(base + "/harness", {waitUntil:"domcontentloaded"});
    await mobile.waitForFunction(() => typeof Harness !== "undefined" && Harness.ready);
    await mobile.locator("#archiveBtn").click();
    await mobile.locator("#archiveCid").fill(cid); await mobile.locator("#archiveOpen").click();
    await mobile.getByRole("button", {name:"archive-demo/README.md",exact:true}).click();
    await mobile.locator("#archivePreview .mdview").waitFor();
    const bounds = await mobile.locator("#archiveInspector").boundingBox();
    assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 391 && bounds.y >= 0 && bounds.y + bounds.height <= 845);
    assert.equal(await mobile.locator("#archiveInspector").evaluate(el => el.scrollWidth <= el.clientWidth), true);
    await mobile.screenshot({path:path.join(output,"mobile-inspector.png")});
    await mobile.getByRole("button",{name:"Close archive",exact:true}).click();
    await page.locator("#archiveBtn").click();
    const large = Buffer.from("frame boundary\n".repeat(5000));
    await page.locator("#archiveFile").setInputFiles({name:"frames.zip",mimeType:"application/zip",buffer:Buffer.from(zip.zipSync({"fresh/large.txt":large,"fresh/sibling.txt":Buffer.from("sibling")}))});
    await page.waitForFunction(() => document.querySelectorAll("#archiveEntries li").length === 2);
    const freshCid = await page.locator("#archiveCid").inputValue();
    await page.getByRole("button",{name:"fresh/large.txt",exact:true}).click();
    await page.locator("#archivePreview .blob-ref").click();
    await page.locator(".graal-file-dialog .codeview").waitFor();
    await page.getByRole("button",{name:"Close file viewer",exact:true}).click();
    await page.getByRole("checkbox",{name:"Select fresh/sibling.txt",exact:true}).uncheck();
    waiting = page.waitForEvent("download"); await page.locator("#archiveDownload").click(); downloaded = await waiting;
    assert.deepEqual(await fs.readFile(await downloaded.path()), large);
    await page.waitForFunction(() => !document.querySelector("#archiveDownload").disabled);
    await page.locator("#archiveLandscape").click();
    assert.equal(await page.evaluate(cid => {
      const nodes=G.nodes.filter(n=>n.params?.archiveCid===cid&&n.type==="note");
      if(nodes.length!==2)return false;
      const a=nodes[0].el.getBoundingClientRect(),b=nodes[1].el.getBoundingClientRect();
      return a.right<=b.left+1||b.right<=a.left+1||a.bottom<=b.top+1||b.bottom<=a.top+1;
    },freshCid),true,"fresh archive receives layout before fitting");
    await page.locator("#archiveBtn").click();
    await page.locator("#archiveFile").setInputFiles({name:"unsafe.zip",mimeType:"application/zip",buffer:Buffer.from(zip.zipSync({"../escape.txt":Buffer.from("rejected")}))});
    await page.waitForFunction(() => document.querySelector("#archiveStatus").textContent.includes("Unsafe archive path"));
    assert.equal(await page.locator("#archiveEntries li").count(),2,"rejected import preserves the previous archive");
    await page.route("**/archive-worker.js", route => route.fulfill({contentType:"application/javascript",body:"self.onmessage = () => {};"}));
    await page.locator("#archiveDemo").click();
    await page.locator("#archiveCancel").click();
    await page.waitForFunction(() => document.querySelector("#archiveStatus").textContent.startsWith("Cancelled locally"));
    assert.equal(await page.locator("#archiveDemo").isEnabled(),true);
    assert.deepEqual(errors, []);
    console.log(JSON.stringify({cid,output,checks:["worker import","Graal preview","single restore","selective ZIP restore","nested landscape","no sibling overlaps","painted canvas","wheel zoom and blob opener","published reload","mobile reopen","multi-frame CID opener and restore","unsafe import retains previous archive","worker cancellation","no page errors"]},null,2));
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
