package borg.trikeshed.util.oroboros

import borg.trikeshed.job.ContentId
import borg.trikeshed.lib.Series
import borg.trikeshed.lib.j

/** Lexical memory retained from an agent call without retaining mutable state. */
data class LexicalMemory(
    val summary: String,
    val title: String,
    val content: String,
) {
    val terms: Set<String> get() = tokenize("$summary $title $content")

    fun overlap(other: LexicalMemory): Int = terms.count { it in other.terms }

    /**
     * Line-CAS proximity against [other]: trim→CAS each line, stamp bidirectional
     * 2-hex neighbor prefixes, score LINKED > PARTIAL > CONTENT_ONLY.
     * Structural reuse (same line + same neighborhood) beats bare term overlap
     * for long-form agent text where boilerplate terms collide.
     */
    fun lineCasProximity(other: LexicalMemory): Double {
        val a = borg.trikeshed.cas.LineCas.spine("$summary\n$title\n$content")
        val b = borg.trikeshed.cas.LineCas.spine("${other.summary}\n${other.title}\n${other.content}")
        return borg.trikeshed.cas.LineCas.proximity(a, b)
    }

    companion object {
        private fun tokenize(text: String): Set<String> = text
            .lowercase()
            .split(Regex("[^a-z0-9]+"))
            .asSequence()
            .filter { it.length > 2 }
            .toSet()
    }
}

/**
 * Immutable claim over one mutable producer artifact at the instant it landed.
 *
 * [patchCid] names the exact cumulative patch bytes fetched from the producer.
 * [revision] and [versionTag] name the accepted repository state. Follow-up work
 * cites this receipt as parent evidence; it never resumes the mutable producer
 * session after merge.
 */
/** The exact producer artifact whose bytes authorize this receipt. */
enum class ReceiptArtifactKind { PATCH, REPORT }

data class MergeReceipt(
    val workId: String,
    val producer: String,
    val producerRef: String,
    val patchCid: ContentId,
    /**
     * Structured artifact identity. [patchCid] is retained as the historical
     * wire/property name; [artifactCid] is the kind-neutral projection.
     */
    val artifactKind: ReceiptArtifactKind = ReceiptArtifactKind.PATCH,
    val revision: String,
    val versionTag: String,
    val lexicalMemory: LexicalMemory,
    val claimedAt: Long,
    /**
     * Optional URL tying this receipt to the upstream merge surface. The Jules
     * session id ([producerRef]) is the canonical ticket; Jules holds the
     * generated bytes, we hold the merged+committed bytes, and the receipt
     * bridges them. This url may be a PR URL or a `refs/heads/jules-<id>-*`
     * branch URL fished from origin, and it is OPTIONAL — a receipt stands
     * with or without a PR (Jules pushes branches, not PRs). null means no
     * upstream surface was found; the receipt is still provenance-complete via
     * [patchCid] + [revision] + [versionTag].
     */
    val prUrl: String? = null,
) {
    val artifactCid: ContentId get() = patchCid
}

/**
 * Immutable claim over one historical agent artifact stored in Oroboros CAS.
 *
 * Session history is a locator and donor, never repository truth. [artifactCid]
 * names the exact exported transcript bytes; Git revisions and producer refs are
 * evidence anchors extracted from those bytes for later verification against
 * Git objects and paginated producer activity.
 */
data class ExposureReceipt(
    val sourceSession: String,
    val sourceMessage: String?,
    val observedAt: Long,
    val lexicalMemory: LexicalMemory,
    val filePaths: Series<String>,
    val artifactCid: ContentId,
    val gitRevisions: Series<String> = 0 j { "" },
    val producerRefs: Series<String> = 0 j { "" },
    val versionTags: Series<String> = 0 j { "" },
    val parentReceipt: ContentId? = null,
)

/** Point-in-time inputs to the induction gate. */
